### ISSUE TITLE
Cant open the gitbook link

### ISSUE THREAD

**Issue by prasadhewage** [react-made-native-easy/book#33]
Can you verify if the gitbook link is correct?

**Comment by master-atul** [comment]
Hi @prasadhewage 
I was able to download the book from gitbook link. 
Here are the pdf, epub and mobi versions if you are not able to access the actual link: https://github.com/react-made-native-easy/book/releases/tag/12.11.18

If you are suggesting that reactnative.guide itself is not working? - Please try it on a different network and browser.  I recently switched the domain provider from godaddy to google domains. So it might lead to cache issues with certain network providers.
