### ISSUE TITLE
Hi there, this book is really great, but the site to read it is unavailable currently

### ISSUE THREAD

**Issue by SeasonLeee** [react-made-native-easy/book#39]
What happen?

**Comment by a7ul** [comment]
Hi @SeasonLeee  is it still the case ? The site looks up https://www.reactnative.guide/ at the moment.

**Comment by SeasonLeee** [comment]
@a7ul Hey, thanks for the response, I just checked, it works now!

I will close the issue~

And thanks for the great knowledge sharing project~
